### ISSUE TITLE
for apm plugin,if i changed group by ,change back,n/a

### ISSUE THREAD

**Issue by dtbdtb** [rafal-szypulka/grafana-ibm-apm#12]
for apm plugin,one metric work fine,if change the group by,n/a,but you said that only primary key can be group by,so i can accept it ,so i change back,but also keep n/a
why ?
it seems that plugin is not stable

**Comment by rafal-szypulka** [comment]
I created a test release with a fix that should work on both Grafana 4.5.2 and 4.6.x. 
If you want to test it, here are the steps:
- move existing ibm apm plugin directory grafana-ibm-apm* from /var/lib/grafana/plugins to different location
- Download new version from https://github.com/rafal-szypulka/grafana-ibm-apm/releases/tag/v0.7-alpha or run `git clone -b 0.7-pre1 https://github.com/rafal-szypulka/grafana-ibm-apm` and copy to /var/lib/grafana/plugins
- restart Grafana server

Let me know if it works for you.
