### ISSUE TITLE
last 1 hr,but not right

### ISSUE THREAD

**Issue by dtbdtb** [rafal-szypulka/grafana-ibm-apm#13]
hi
every one 
my version is 452
and my time range is last 1 hr 
and time in grafana server is : Sun Nov  5 21:46:12 CST 2017
and my notebook time is 20171105,21:56
and my query url is :  
http://dtbdtb.oicp.net:9008/api/datasources/proxy/1/datasources/TMSAgent.%25IBM.KSG/datasets/MetricGroup.KSGHYPERVS/items?optimize=true&param_SourceToken=in3:icm:SG&param_Time=20171105T125319--20171105T135319&param_refId=1396487587635&properties=VCPU_RATE,WRITETIME,REGI_NAME

time range is 20171105T125319--20171105T135319
why ?
8 hours offset ?
where should i modify ?
thank you

**Comment by rafal-szypulka** [comment]
In the datasource configuration you have an option to set UTC timezone offset. If you connect to ITM6, set data provider version: 6.x and UTC offset for the timezone of your HUB TEMS. Let me know if it works.
