### ISSUE TITLE
Strings attributes not displaying in Grafana

### ISSUE THREAD

**Issue by jerryemby** [rafal-szypulka/grafana-ibm-apm#16]
Please include this information:

- What Grafana version are you using?
- What IBM APM datasource version are you using and how you installed it (git clone/downloaded git release/grafana-cli) ?V0.7 with fix for Make strings and dates displayable 
- What OS are you running grafana on? RHEL 6.5
- What did you do? I select a attribute that returns a string
- What was the expected result? Display a Sting attribute
[grafana issue.docx](https://github.com/rafal-szypulka/grafana-ibm-apm/files/1781805/grafana.issue.docx)

- What happened instead? I get a - displayed
- If related to metric query / query editor:
Include raw network request & response: get by opening Chrome Dev Tools (F12, Ctrl+Shift+I on windows, Cmd+Opt+I on Mac), go the network tab.
 
The returning data is correct, it is not being displayed correctly in Grafana. 

":"Mar 5, 2018 10:21:48 AM"}],"tooltip":"","label":"","typeLabel":"","type":"","id":"0_621"},{"properties":[{"value":"Primary","label":"gtmsConfigPeerNodeRole","valueType":"string","id":"GTMSCONFI1"},{"value":"2018-03-05T10:22:48","label":"Timestamp","valueType":"isodatetime","id":"TIMESTAMP","displayValue":

**Comment by jerryemby** [comment]
I tested with the standard Linux LZ agent and tried to display the mount point for the file systems and it also couldn't not display the string.

**Comment by rafal-szypulka** [comment]
Please try to set Options->Table transform-> Time series to rows

**Comment by jerryemby** [comment]
No change, that just placed the name of the attribute on the row but the data is still a dash “–“.  Regards Jerry


[cid:image001.jpg@01D3B516.711584E0]

**Comment by rafal-szypulka** [comment]
Maybe the parameter value is kept in the `value` item in the json response instead of `displayValue`...
Try to change `Value Attribute` to `value` instead of `displayValue` in the panel query editor and click refresh icon (it won't refresh automatically like for other parameters). Option `Time series to rows` also must be enabled. For Linux OS Disk it works:
![image](https://user-images.githubusercontent.com/11664393/37033075-e99efdd4-2144-11e8-9da2-b0a2be076a9c.png)

**Comment by jerryemby** [comment]
Rafal,

            Changing the Value Attribute to value did the trick,  I will test it out today with other string attributes.  Thanks Jerry

**Comment by jerryemby** [comment]
Rafal,

            One other question, there seems to be a limitation on the Metric Name to 10 characters.  Is there a way to make that larger?  Jerry

[cid:image001.png@01D3B52D.382CEB20]

**Comment by rafal-szypulka** [comment]
@jerryemby,  If you think it is a plugin code problem, please open another issue, attach a screenshot or describe the problem in more details. Original issue has been solved, so I am closing it.
