### ISSUE TITLE
IBM TIV 6.3 FP7 - Request for large queries causes TEPS to go offline.

### ISSUE THREAD

**Issue by dan-nadel** [rafal-szypulka/grafana-ibm-apm#19]
Hello,

When users select time ranges greater than 24 hours for Tivoli 6.3 datasource in Garafana, the TEPS server java process spikes CPU and then TEPS becomes unusable.  We then need to restart TEPS.  Have opened ticket with IBM,  Any suggestions to stabilize the tool would be helpfull.

**Comment by rafal-szypulka** [comment]
@dan-nadel Please check if you have the same errors in the SystemOut.log on TEPS as reported here: https://github.com/rafal-szypulka/grafana-ibm-apm/issues/7

**Comment by dan-nadel** [comment]
Yes,

[5/11/18 11:55:26:237 EDT] 00000794 rest          E com.ibm.tivoli.rest.RestRequestProcessor handleRequest unexpected exception:
                                 javax.servlet.ServletException: java.lang.OutOfMemoryError: Java heap space

Does this error indicate we are running out of JAVA memory?

**Comment by dan-nadel** [comment]
Increased my heap size, looks like this helped.

https://www.ibm.com/support/knowledgecenter/en/SS3JRN_7.2.1/com.ibm.itm.doc_6.3/trouble/teps_tepseheapsize_trouble.htm
