### ISSUE TITLE
Plugin sends incorrect value for param_SourceToken

### ISSUE THREAD

**Issue by tysonrm** [rafal-szypulka/grafana-ibm-apm#24]
Plugin sends incorrect value for param_SourceToken.

For instance,

Plugin sends param_SourceToken=Primary:ab3_vm00001948:NT

When it should send:

param_SourceToken=ab3_vm00001948:NT

In a nutshell, it is tacking on a Primary: when it should not... as Primary is not list in the TEMS list.

tivlls@nl03hts021ccpxa:/opt/IBM/TEMS/bin> tacmd listsystems -t NT | grep vm00001948
ab3_vm00001948:NT NT 06.30.07.00 Y

Note that there are a lot of systems that do have a "Primary" on them
Primary:ab3_nl0311AB33169:NT NT 06.30.07.00 Y
Primary:ab3_nl0311AB36501:NT NT 06.30.07.00 Y
Primary:ab3_nl0311AB31879:NT NT 06.30.07.00 Y

so the rule is not universal. Why one is and one is not is not clear to me.

- What Grafana version are you using?
- What IBM APM datasource version are you using and how you installed it (git clone/downloaded git release/grafana-cli) ?
- What OS are you running grafana on? 
- What did you do?
- What was the expected result?
- What happened instead?
- If related to metric query / query editor:
Include raw network request & response: get by opening Chrome Dev Tools (F12, Ctrl+Shift+I on windows, Cmd+Opt+I on Mac), go the network tab.

**Comment by rafal-szypulka** [comment]
As per offline conversation, this problem came from the code added to modified/non-public version of the plugin.
