### ISSUE TITLE
Datasource problem

### ISSUE THREAD

**Issue by sambr7** [rafal-szypulka/grafana-ibm-apm#3]
Hi Rafal,

When I add the datasource on Grafana it works correctly, however when I try to copy your dashboards or even create another on my own I got the error "Server response 404" and "Server response: 500".

I'm using ITM63 only as a datasource, here's the connection URI for my server:

http://my.ip.address:15200/ibm/tivoli/rest/providers/itm.hub.myhostname

![image](https://user-images.githubusercontent.com/6661354/30401342-53312a9c-98b0-11e7-98c7-60faca938b7b.png)

Could you please advise?
Thank you.

**Comment by rafal-szypulka** [comment]
Hi, For ITM6 the connection should be specified in the following form:
http://<teps_server_hostname>:15200/ibm/tivoli/rest/providers/itm.<TEMS_NAME>
where TEMS_NAME is a HUB TEMS label (not hostname). Usually it is TEMS or HUB_TEMS.
Please check this URL: http://<TEPS_IP>:15200/ITMRESTProvider/test.html, logon as sysadmin then put /ibm/tivoli/rest/providers in the URI field and then click Get. Check the "uri" parameter.

![image](https://user-images.githubusercontent.com/11664393/30425004-0127e8d8-9948-11e7-9121-ec147aa7f552.png)

If it didn't help, check Troubleshooting section of the plugin documentation. Open Web Browser console and check what request goes to ITM API and what is the response.
Example dashboard for Linux OS will work only if you have some Linux OS agents connected to your ITM server.

**Comment by sambr7** [comment]
Hi Rafal,

Thanks for your quick response.
My URI looks like this:

![image](https://user-images.githubusercontent.com/6661354/30444939-f1628990-995a-11e7-90e4-a06a30b6a4d7.png)

It´s configured exactly as yours, the only difference is that my HUB TEMS name has a dot "." in its name.
For example: hub.`uname -n`...

**Comment by sambr7** [comment]
Hi Rafal,

Problem solved.
Apparently I had 2 problems:

1. My HUB TEMS name is hub.hostname and it's not supported (or your datasource can't recognize it), so I've used the Domain Override option to set the standard "TEMS" name into TEPS.
2. For some reason, authorization policies option was checked. It is unchecked now and it's working fine.


![image](https://user-images.githubusercontent.com/6661354/30458734-425822ba-9983-11e7-8e56-9f7ce44f5a54.png)

Thank you.
Best regards,

Samuel Januario

**Comment by rafal-szypulka** [comment]
Hi Samuel, Glad to hear it works. Do you know which setting solved the problem? TEMS label, authorization policy or both? My guess is that authorization policy could be the reason, as it could limit the data provided by cURI Data Provider. If you could test it (I mean disable both Domain override and authorization policy, reconfigure and restart TEPS) , that would be great. No worries if you can't. 
If you see these kind of problems, it is always good to [check the browser console](https://webmasters.stackexchange.com/questions/8525/how-do-i-open-the-javascript-console-in-different-browsers), because there is a chance you will find more meaningful error message there. 
Regards, Rafal

**Comment by sambr7** [comment]
Hi Rafal,

Surprisingly it worked this time. I guess there was something wrong with my TEPS.
Thanks for your support.

Best regards,
Samuel Januario

**Comment by sambr7** [comment]
Hi Rafal,

I've disabled the domain override and reconfigured the Datasource in Grafana and it worked fine for some time (perhaps the cache helped the data to stay in the dashboard). After some time it stopped working and I went through the Datasouce tab in Grafana to check the connection and I've got this:

`Object { name: "IBM APM", type: "datasource", id: "ibm-apm-datasource", enabled: false, pinned: false, module: "plugins/ibm-apm-datasource/module", baseUrl: "public/plugins/ibm-apm-datasource", info: Object, includes: null, dependencies: Object, 5 more… }  ds_edit_ctrl.js:4:1573
`
This time I didnt use the "authorization policies" option.

Best regards,
Samuel Januario

**Comment by rafal-szypulka** [comment]
The issue was confirmed by other user. I updated documentation with suggestion that recommended solution is to use TEPS Domain Override option.
