### ISSUE TITLE
No metrics with Agent Instace value rs41:LZ

### ISSUE THREAD

**Issue by himuura** [rafal-szypulka/grafana-ibm-apm#32]
Please include this information:

- What Grafana version are you using?
6.7.3
- What IBM APM datasource version are you using and how you installed it (git clone/downloaded git release/grafana-cli) ?
0.90, via git.
- What OS are you running grafana on?
RHEL 7.7
- What did you do?
Imported the sample Linux dashboard.
- What was the expected result?
Being able to see the graphs without manually changing the Agent Instance value from the dropdown list (rs41:LZ)
- What happened instead?
No value shown if the agent instance value is set to rs41:LZ.
- If related to metric query / query editor:
Include raw network request & response: get by opening Chrome Dev Tools (F12, Ctrl+Shift+I on windows, Cmd+Opt+I on Mac), go the network tab.

If the agent instace value is changed to a value from the dropdown list, values are shown. If the rs41:LZ value is used instead an error pops up:

Server Response: 500, Message: ATKRST100E An unexpected error occured. The error message is as follows: 'com.ibm.usmi.console.navigator.model.NavExceptionKFWITM633E Exception: KFWITM775E Request failed due to invalid managed system(s) or resource group(s): rs41:LZ: nested exception is: com.ibm.tivoli.monitoring.provider.navmodel.ITMRuntimeException: KFWITM775E Request failed due to invalid managed system(s) or resource group(s): rs41:LZ'.

**Comment by himuura** [comment]
changed Agent Instance to $AgentName and it seems to be working...is it the correct way?

**Comment by rafal-szypulka** [comment]
Yes, this is correct, thanks for pointing this out. I fixed it in the sample dashboard.

**Comment by himuura** [comment]
just a quick question (to spare another post :P ) you agents dashboard detects both my AIX systems and Linux. Is it possible to get the Linux Dashboard to show both AIX and Linux? or to create a new dash using the same model as the linux dash but for aix? what needs to be changed in the JSON in order to get this?

**Comment by rafal-szypulka** [comment]
You would need to change multiple things in JSON because AIX is monitored
with different agent type, so attribute names and attribute groups are
probably different. I would make a copy of linux dashboard (save with
another name in grafana), edit each panel, change agent type (select Unix
OS Agent from the dropdown list), att group, and metric names and that's it.

**Comment by himuura** [comment]
Thank you a lot mate!! You've been a great help!

**Comment by himuura** [comment]
Weird, in AIX the variable $AgentName doesnt work...any way to dinamically solve this?

**Comment by rafal-szypulka** [comment]
You need to change the template variable definition. Go to AIX dashboard
settings -> Variables -> $AgentName variable and change the affinity from
TMSAgent.%IBM.STATIC134 to TMSAgent.%25IBM.STATIC013

**Comment by himuura** [comment]
I cant thank you enough mate!

Rafal Szypulka <notifications@github.com> escreveu no dia quinta,
21/05/2020 à(s) 15:35:
