### ISSUE TITLE
[Info] WebSphere Variables

### ISSUE THREAD

**Issue by himuura** [rafal-szypulka/grafana-ibm-apm#35]
This is not an error per se, but is there any link to the IBM documentation regarding the metrics and what they do? For instance, i have ABSF_THR. What is this? What is it related to? I know it's for threads but what's the different between ABSF_THR and NUM_ACTTHR?
Any help will be well received!

**Comment by rafal-szypulka** [comment]
I am not aware of any public documentation for this topic. You can collect this information directly from the ITM API, but it's not documented and quite difficult to explain here. 
The easiest way I know to collect this information is to use my other tool https://github.com/rafal-szypulka/itm_exporter/releases. 
1. Prepare config.yaml as explained in https://github.com/rafal-szypulka/itm_exporter
These 5 lines should be sufficient:
```
itm_server_url: "http://localhost:15200"
itm_server_user: "sysadmin"
itm_server_password: "pass"
connection_timeout: 8
collection_timeout: 40
```
then
```
itm_exporter listAgentTypes --temsName=<TEMS label ex. TEMS>
```
then
```
itm_exporter listAttributeGroups --dataset=<dataset URI for WAS agent>
```
then
```
itm_exporter listAttributes --attributeGroup=<attribute group id> --dataset=<dataset URI for WAS agent>
```
The output should be similar to (example for Linux OS Agent, KLZCPU group):
```
+------------------------------+------------+-------------+
|         DESCRIPTION          | ATTRIBUTES | PRIMARY KEY |
+------------------------------+------------+-------------+
| System Name                  | ORIGINNODE | false       |
| Time Stamp                   | TIMESTAMP  | false       |
| CPU ID                       | CPUID      | true        |
| User CPU (Percent)           | USRCPU     | false       |
| User Nice CPU (Percent)      | USRNCPU    | false       |
| System CPU (Percent)         | SYSCPU     | false       |
| Idle CPU (Percent)           | IDLECPU    | false       |
| Busy CPU (Percent)           | BUSYCPU    | false       |
| I/O Wait (Percent)           | WAITCPU    | false       |
| User to System CPU (Percent) | USRSYSCPU  | false       |
| Steal CPU (Percent)          | STEALCPU   | false       |
| Recording Time               | WRITETIME  | false       |
+------------------------------+------------+-------------+
```

**Comment by himuura** [comment]
This is a tremendous help mate!! Thank you! Spoke to an IBM representative in my company, and these metrics were indeed available in the CAPM / APM WIM documentation. The documents are named: APM WebSphere Infrastructure Manager agent Reference and APM WebSphere Applications agent Reference (if anyone is interested). You approach is indeed more pragmatic, will definetely use it! Again, thank you for all your help!
