### ISSUE TITLE
Cannot display string metric from ITM v6 through "Status Panel"

### ISSUE THREAD

**Issue by zantark** [rafal-szypulka/grafana-ibm-apm#4]
Hi Rafal,

First, many thanks for this datasource. It is very nice being able to query the ITM wharehouse with grafana !

I recently tried to use it with the "status panel" (https://grafana.com/plugins/vonage-status-panel) and had an issue handling string metrics.
I don't know if it's a compatibility problem between the panel and the datasource or the datasource that does not provide the awaited answer.
I've seen that the datasource does not return a "display value" in case of a string metric, which is not the case with numeric ones. 

Can you have a look ?

Here's an example:

![image](https://user-images.githubusercontent.com/2169104/30693582-84533afe-9ed0-11e7-9c2f-762d52762cad.png)

![image](https://user-images.githubusercontent.com/2169104/30693634-c2edcfc2-9ed0-11e7-83e7-fc8c779e3caf.png)

Thanks for your help.

**Comment by rafal-szypulka** [comment]
Hi, plugin currently supports only numeric metrics. I agree that for panels like the one you used, it would be useful to query also string metrics. I will think about how to solve it.

**Comment by rafal-szypulka** [comment]
Solved with #15
