### ISSUE TITLE
[Grafana Alerts] How to circumvent this issue?

### ISSUE THREAD

**Issue by himuura** [rafal-szypulka/grafana-ibm-apm#45]
- What Grafana version are you using?
 8.0.2

- What IBM APM datasource version are you using and how you installed it (git clone/downloaded git release/grafana-cli) ?
 Git Clone (0.9.1)

- What OS are you running grafana on?
 RHEL 7

- What did you do?
 Trying to create alerts on Grafana after successfully configuring the plugin.

- What was the expected result?
 Alerts should be configurable.

- What happened instead?
 In all the dashboards using the IBM APM datasource i have the message in the Alert section "The datasource does not support alerting queries"

**Comment by rafal-szypulka** [comment]
Only backend data sources support alerting: https://grafana.com/docs/grafana/latest/alerting/unified-alerting/?pg=docs#alert-evaluation This plugin is not a backend data source.
