### ISSUE TITLE
DataSource Issue - APM 8.1.4

### ISSUE THREAD

**Issue by tfcarv** [rafal-szypulka/grafana-ibm-apm#6]
Hello Rafal,

I have upgraded the APM from 8.1.3 to 8.1.4, after that the Datasource communication stopped:

I am using the URL: **http://ibmsvvux0002:8090/ibm/tivoli/rest/providers/itm.KD8**
please have a look on the imagem below:
![captura de tela de 2017-10-09 16-35-54](https://user-images.githubusercontent.com/32651670/31355285-0305f54c-ad10-11e7-8377-fca6bdbaf149.png)

Checking the Grafana Logs its showing this:

t=2017-10-09T15:30:44-0300 lvl=eror msg="Basic auth failed" logger=context error="User not found"
t=2017-10-09T15:30:44-0300 lvl=info msg="Request Completed" logger=context userId=0 orgId=0 uname= method=GET path=/api/datasources/proxy/1 status=401 remote_addr=10.105.164.9 time_ms=0 size=31 referer=http://ibmsvvux0001:3000/datasources/edit/1

Do you know if there is any kind of issue on the new APM Version?

**Comment by rafal-szypulka** [comment]
I did a quick test with APM 8.1.4 and plugin worked. 401 means authorisation problem, so first please try to authenticate directly using smadmin user with this URL in the browser:  http://ibmsvvux0002:8090/ITMRESTProvider/test.html to make sure everything is fine with your smadmin user and password.
