### ISSUE TITLE
Data source connection problem. Server response code: 401

### ISSUE THREAD

**Issue by mno00** [rafal-szypulka/grafana-ibm-apm#8]
Hi Experts 

we have been facing problems when trying to connect to the Data source for our IBM APM application, the process that we follow is to click Grafana Logo -> Data Sources -> IBM APM Datasource -> Edit Data Source.  There we filled all the required fields including basic Auth Details with smadmin user and password.. the issue comes when we click on Save and Test a pop up is prompted asking for user and password for http://SERVERIP:3000  ; we have tried different user combinations with no success, the error that prompts is "Data source connection problem. Server response code: 401" even if no user and password is used the same error is prompted, please any help is appreciated

**Comment by rafal-szypulka** [comment]
401 means authorization problem. If you are not sure about the smadmin password, try to directly access this URL http://<apm_ip>:8090/ITMRESTProvider/test.html via browser. It should ask for authentication. Authenticate using the same smadmin user. If it works, it should work with the plugin, if not then there is a problem on APM side or you doesn't have correct password.
