### ISSUE TITLE
After version 0.6 can not select agent type when adding an ITM metric

### ISSUE THREAD

**Issue by jripollv** [rafal-szypulka/grafana-ibm-apm#9]
After version 0.6 when adding an ITM metric  I can not select agent type, it reverts always to Select Agent Type...

**Comment by rafal-szypulka** [comment]
Hmm, for me it works correctly... this dropdown list is built dynamically via API call. You may check in your browser developer tools what http call is done when you click on select agent type dropdown list and what is the result. 
After you identify the request (it should be similar to: `http://<grafana_url>/api/datasources/proxy/<some_number>/datasources` you can use curl to run this request manually and check the results:
`curl -u grafana_user:grafana_password http://<grafana_url>/api/datasources/proxy/<some_number>/datasources`
How did you install the plugin? `git clone ...` or from release tgz?

**Comment by rafal-szypulka** [comment]
I think, I recreated the issue on Grafana 4.6. I would recommend to use Grafana 4.5.2 until I fix it.

**Comment by rafal-szypulka** [comment]
I created a test release with a fix that should work on both Grafana 4.5.2 and 4.6.x. 
If you want to test it, here are the steps:
- move existing ibm apm plugin directory grafana-ibm-apm* from /var/lib/grafana/plugins to different location
- Download new version from https://github.com/rafal-szypulka/grafana-ibm-apm/releases/tag/v0.7-alpha or run `git clone -b 0.7-pre1 https://github.com/rafal-szypulka/grafana-ibm-apm` and copy to /var/lib/grafana/plugins
- restart Grafana server

Let me know if it works for you.

**Comment by jripollv** [comment]
Now I can add a Metric but I've found something strange in the properties list of the DELETE method:
There is a  **Select Display Item..** property (?):

xhrStatus:"complete"
request:Object
method:"DELETE"
url:"api/datasources/proxy/2/datasources/TMSAgent.%25IBM.STATIC021/datasets/MetricGroup.NTMEMORY"
params:Object
param_SourceToken:"Primary:SPMON:NT"
optimize:"true"
param_Time:"20171030T111142--20171106T111142"
properties:"TOTMEMKB,TIMESTAMP,**Select Display Item..**."
condition:undefined
param_refId:1294111358580
response:Object

**Comment by rafal-szypulka** [comment]
Yeah.. it looks ugly (if someone notice), but works. It happens only for attribute groups that return single row (no primary key/display item).
